### ISSUE TITLE
Write presentation

### ISSUE THREAD

**Issue by tomdevman** [cldme/aws-lambda#8]

**Comment by tomdevman** [comment]
What shall we do for the presentation ? Is this clear to you ? Perhaps we should ask a question on Mattermost of what needs to be done for the presenation (slides/video ?)

**Comment by jwbambacht** [comment]
I have no idea what they want. Maybe best to propose to create a video with slides? I’m not sure if a presentation with 4 persons over zoom will be the best way to do it. The other groups also need to learn about it, which is not very useful if it is messy.
